#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        create_flexvol_perf.py
# Author:       Ronald Feist
# Date:         2020-06-10
# Description:  Create a volume on the aggregate with the most headroom
#               with Ansible modules
#
# Modules:      na_ontap_volume, na_ontap_aggregate
#
# URLs:         http://docs.netapp.com/ontap-9/index.jsp
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.na_ontap_volume
#
################################################################################

- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname:       "{{ PRI_CLU }}"
      username:       "{{ PRI_CLU_USER }}"
      password:       "{{ PRI_CLU_PASS }}"
      https:          true
      validate_certs: false
      use_rest:       Always
  vars_files:
    - global.vars
  collections:
    - netapp.ontap
  tasks:
  - name: Create volume on primary SVM
    na_ontap_volume:
      state:                 present
      name:                  "{{ PRI_SVM }}_vol_01"
      vserver:               "{{ PRI_SVM }}"
      size:                  "{{ VOL_SIZE }}"
      size_unit:             gb
      aggregate_name:        "{{ PERF_AGGR }}"
      comment:               Created with Ansible
      space_guarantee:       volume
      policy:                default
      volume_security_style: unix
      <<: *input
