---
- hosts: localhost
  name: Get ONTAP Cluster Information
  vars:
    input: &input
      hostname:       "{{ PRI_CLU }}"
      username:       "{{ PRI_CLU_USER }}"
      password:       "{{ PRI_CLU_PASS }}"
      https:          true
      validate_certs: false
      use_rest:       Always
  vars_files:
    - global.vars
  collections:
    - netapp.ontap
  tasks:
  - name: gather info
    na_ontap_info:
      state: info
      <<: *login
      gather_subset:
      - lun_info
    register: ontap_info
  - debug:
     msg: "{{ ontap_info.ontap_info }}"
