#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        create_volume.yml
# Author:       Victor Franco
# Date:         2020-06-12
# Description:  Create a volume
#               with Ansible modules
#
# Modules:      na_ontap_volume
#
# URLs:         http://docs.netapp.com/ontap-9/index.jsp
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.na_ontap_volume
#
################################################################################

- hosts: localhost
  gather_facts: false
  vars:
 # Create a volume called nas_svm_cifs_01 of size 20MB in the SVM nas_svm and aggregate aggr1_cluster1_01_data.
    volume_name: nas_svm_cifs_01
    volume_size: 20
    volume_unit: mb
    svm_name: nas_svm
    aggregate_name: aggr1_cluster1_01_data
    input: &input
      hostname:       "{{ PRI_CLU }}"
      username:       "{{ PRI_CLU_USER }}"
      password:       "{{ PRI_CLU_PASS }}"
      https:          true
      validate_certs: false
# root_volume_aggregate currently not supported with REST
#      use_rest:       Always
  vars_files:
    - global.vars
  collections:
    - netapp.ontap

  tasks:
  - name: Create volume
    na_ontap_volume:
      state: present
      name: "{{ volume_name }}"
      size: "{{ volume_size }}"
      size_unit: "{{ volume_unit }}"
      vserver: "{{ svm_name }}"
      aggregate_name: "{{ aggregate_name }}"
#      is_infinite: False
#      user_id: 1001
#      group_id: 2002
#      space_guarantee: none
#      tiering_policy: auto
#      export_policy: default
#      percent_snapshot_space: 60
#      qos_policy_group: max_performance_gold
#      wait_for_completion: True
#      space_slo: none
#      nvfail_enabled: False
      comment:               Created with Ansible
      <<: *input

