#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        create_share.yml
# Author:       Victor Franco
# Date:         2021-07-15
# Description:  Create a CIFS share
#               with Ansible modules
#
# Modules:      na_ontap_cifs
#
# URLs:         http://docs.netapp.com/ontap-9/index.jsp
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.na_ontap_cifs
#
################################################################################

- hosts: localhost
  gather_facts: false
  vars:
 # Create a CIFS share share_01 in the SVM nas_svm.
    share_name: share_01
    svm_name: nas_svm
    aggregate_name: aggr1_cluster1_01_data
    input: &input
      hostname:       "{{ PRI_CLU }}"
      username:       "{{ PRI_CLU_USER }}"
      password:       "{{ PRI_CLU_PASS }}"
      https:          true
      validate_certs: false
# root_volume_aggregate currently not supported with REST
#      use_rest:       Always
  vars_files:
    - global.vars
  collections:
    - netapp.ontap

  tasks:
  - name: Create a CIFs share
    na_ontap_cifs:
      state: present
      share_name: "{{ share_name }}"
      vserver: "{{ svm_name }}"
      path: /
#      share_properties: browsable,oplocks
#      symlink_properties: read_only,enable
#      comment: CIFS share description
      <<: *input

